# Rename this file to config.yaml and fill in the fields

# See https://github.com/alexa-pi/AlexaPi/wiki/Audio-setup-&-debugging
# to get a better idea of how to set things in here
sound:
  # Name of your ALSA microphone/soundcard in arecord -L
  # you can also try setting it to 'default'
  input_device: "plughw:1"

  # you can go here with alsa, pulse or others
  # keep blank for the best audio output selected by the underlying code
  output: "alsa"
  # output device for the audio output specified above,
  # currently supports ALSA only
  output_device: "default"

# Amazon Alexa settings
alexa:
  Client_ID:
  Client_Secret:
  ProductID:
  Security_Profile_Description:
  Security_Profile_ID:
  refresh_token:

sphinx:
  trigger_phrase: "alexa"

platform:
  # Name of your platform, e.g. raspberrypi, orangepi, desktop
  device: "raspberrypi"

platforms:
  # common config for all platforms (if they support the options)
  # can be overriden in the the respective platform sections
  common:
    # whether you want to hear Alexa's "yes" after you press a button
    # "true" or "false"
    should_confirm_trigger: false

    long_press:
      # system command to run after pressing the button for _duration_ number of seconds
      # empty to disable
      command: ""

      # duration in seconds
      duration: 10

      # CURRENTLY DISABLED
      # optional audio file to play before executing the command
      # you might wanna use full path to make sure AlexaPi finds it
      # you can use {resources_path} for the path to the AlexaPi "resources" directory
      audio_file: ""

  raspberrypi:
    # GPIO Pin with button connected
    button: 18
    # GPIO Pin for the playback/activity light
    plb_light: 24
    # GPIO Pin for the recording light
    rec_light: 25

  orangepi:
    # GPIO Pin with button connected
    button: 20
    # GPIO Pin for the playback/activity light
    plb_light: 9
    # GPIO Pin for the recording light
    rec_light: 8

  desktop:
    should_confirm_trigger: true

    min_seconds_to_record: 3

  dummy:
    # whether to print messages when methods are called
    verbose: false
